/// <reference types=".vue-global-types/vue_3.4_false.d.ts" />
const { defineProps, defineSlots, defineEmits, defineExpose, defineModel, defineOptions, withDefaults, } = await import('vue');
const __VLS_fnComponent = (await import('vue')).defineComponent({});
;
let __VLS_functionalComponentProps;
function __VLS_template() {
    const __VLS_ctx = {};
    const __VLS_localComponents = {
        ...{},
        ...{},
        ...__VLS_ctx,
    };
    let __VLS_components;
    const __VLS_localDirectives = {
        ...{},
        ...__VLS_ctx,
    };
    let __VLS_directives;
    let __VLS_styleScopedClasses;
    __VLS_styleScopedClasses['button7'];
    __VLS_styleScopedClasses['button8'];
    __VLS_styleScopedClasses['segmented-picker3'];
    __VLS_styleScopedClasses['button-container'];
    __VLS_styleScopedClasses['button-container1'];
    __VLS_styleScopedClasses['button-container2'];
    __VLS_styleScopedClasses['button10'];
    __VLS_styleScopedClasses['button11'];
    __VLS_styleScopedClasses['horizontal-container5'];
    __VLS_styleScopedClasses['horizontal-container4'];
    __VLS_styleScopedClasses['horizontal-container3'];
    __VLS_styleScopedClasses['horizontal-container2'];
    __VLS_styleScopedClasses['placeholder'];
    __VLS_styleScopedClasses['podez'];
    __VLS_styleScopedClasses['calendar'];
    __VLS_styleScopedClasses['calendar-container'];
    __VLS_styleScopedClasses['pagination'];
    __VLS_styleScopedClasses['table'];
    __VLS_styleScopedClasses['table-container'];
    __VLS_styleScopedClasses['shaxmatka'];
    __VLS_styleScopedClasses['horizontal-container2'];
    __VLS_styleScopedClasses['table'];
    __VLS_styleScopedClasses['text-input-container1'];
    __VLS_styleScopedClasses['text-input-container2'];
    __VLS_styleScopedClasses['horizontal-container1'];
    __VLS_styleScopedClasses['horizontal-container4'];
    __VLS_styleScopedClasses['horizontal-container5'];
    __VLS_styleScopedClasses['horizontal-container3'];
    __VLS_styleScopedClasses['container1'];
    __VLS_styleScopedClasses['pagination'];
    __VLS_styleScopedClasses['segmented-picker1'];
    __VLS_styleScopedClasses['segmented-picker3'];
    __VLS_styleScopedClasses['pagination'];
    __VLS_styleScopedClasses['table'];
    // CSS variable injection 
    // CSS variable injection end 
    let __VLS_resolvedLocalAndGlobalComponents;
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("shaxmatka") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.header, __VLS_intrinsicElements.header)({ ...{ class: ("text-input") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("horizontal-container") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.img)({ ...{ class: ("image-icon") }, loading: ("lazy"), alt: (""), src: ("/image@2x.png"), });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("text-input-container") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("hakimi-towers") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("dropdown-container") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.select, __VLS_intrinsicElements.select)({});
    __VLS_elementAsFunction(__VLS_intrinsicElements.option, __VLS_intrinsicElements.option)({ value: (""), });
    __VLS_elementAsFunction(__VLS_intrinsicElements.option, __VLS_intrinsicElements.option)({ value: ("1"), });
    __VLS_elementAsFunction(__VLS_intrinsicElements.option, __VLS_intrinsicElements.option)({ value: ("2"), });
    __VLS_elementAsFunction(__VLS_intrinsicElements.option, __VLS_intrinsicElements.option)({ value: ("3"), });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("segmented-picker") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.a, __VLS_intrinsicElements.a)({ ...{ class: ("bino") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("dropdown-container") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.select, __VLS_intrinsicElements.select)({});
    __VLS_elementAsFunction(__VLS_intrinsicElements.option, __VLS_intrinsicElements.option)({ value: (""), });
    __VLS_elementAsFunction(__VLS_intrinsicElements.option, __VLS_intrinsicElements.option)({ value: ("1"), });
    __VLS_elementAsFunction(__VLS_intrinsicElements.option, __VLS_intrinsicElements.option)({ value: ("2"), });
    __VLS_elementAsFunction(__VLS_intrinsicElements.option, __VLS_intrinsicElements.option)({ value: ("3"), });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("vertical-container") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("vertical-container1") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.img)({ ...{ class: ("close-icon") }, loading: ("lazy"), alt: (""), src: ("/close.svg"), });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("horizontal-container1") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("text-input-container1") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("workspace") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("text-input2") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.img)({ ...{ class: ("vertical-container-icon") }, alt: (""), src: ("/vertical-container.svg"), });
    __VLS_elementAsFunction(__VLS_intrinsicElements.input)({ ...{ class: ("qidirish") }, placeholder: ("Qidirish"), type: ("text"), });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("text-input-container2") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("workspace1") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("text-input3") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.input)({ ...{ class: ("xonalar-soni") }, placeholder: ("Xonalar soni"), type: ("number"), });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("segmented-picker1") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("button") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.a, __VLS_intrinsicElements.a)({ ...{ class: ("m2") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.sup, __VLS_intrinsicElements.sup)({});
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("text-input4") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.input)({ ...{ class: ("dan") }, placeholder: ("dan"), type: ("text"), });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("text-input5") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.input)({ ...{ class: ("gacha") }, placeholder: ("gacha"), type: ("text"), });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("segmented-picker1") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("button") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.a, __VLS_intrinsicElements.a)({ ...{ class: ("m2") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("text-input4") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.input)({ ...{ class: ("dan") }, placeholder: ("dan"), type: ("text"), });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("text-input5") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.input)({ ...{ class: ("gacha") }, placeholder: ("gacha"), type: ("text"), });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("segmented-picker1") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("button") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.a, __VLS_intrinsicElements.a)({ ...{ class: ("m2") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("text-input4") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.input)({ ...{ class: ("dan") }, placeholder: ("dan"), type: ("text"), });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("text-input5") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.input)({ ...{ class: ("gacha") }, placeholder: ("gacha"), type: ("text"), });
    __VLS_elementAsFunction(__VLS_intrinsicElements.button, __VLS_intrinsicElements.button)({ ...{ class: ("button5") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.img)({ ...{ class: ("slider-container-icon") }, alt: (""), src: ("/slider-container@2x.png"), });
    __VLS_elementAsFunction(__VLS_intrinsicElements.a, __VLS_intrinsicElements.a)({ ...{ class: ("batafsil") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.img)({ ...{ class: ("text-input-icon") }, alt: (""), src: ("/batafsil.svg"), });
    __VLS_elementAsFunction(__VLS_intrinsicElements.main, __VLS_intrinsicElements.main)({ ...{ class: ("table-container") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.section, __VLS_intrinsicElements.section)({ ...{ class: ("table") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("horizontal-container2") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("segmented-picker3") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.button, __VLS_intrinsicElements.button)({ ...{ class: ("button6") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.img)({ ...{ class: ("card-icon") }, alt: (""), src: ("/card.svg"), });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("royxat") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.button, __VLS_intrinsicElements.button)({ ...{ class: ("button7") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.img)({ ...{ class: ("container-icon") }, alt: (""), src: ("/container.svg"), });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("shaxmatka1") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.button, __VLS_intrinsicElements.button)({ ...{ class: ("button8") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.img)({ ...{ class: ("space-dashboard-icon") }, alt: (""), src: ("/space-dashboard.svg"), });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("shaxmatka2") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("horizontal-container3") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("button9") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("murakkab") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.img)({ ...{ class: ("vertical-container-icon1") }, alt: (""), src: ("/vertical-container-1.svg"), });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("horizontal-container4") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("xonadon") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("horizontal-container5") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.button, __VLS_intrinsicElements.button)({ ...{ class: ("button-container") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.img)({ ...{ class: ("button-container-icon") }, alt: (""), src: ("/button-container.svg"), });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("bosh") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.button, __VLS_intrinsicElements.button)({ ...{ class: ("button-container1") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.img)({ ...{ class: ("button-container-icon1") }, alt: (""), src: ("/button-container-1.svg"), });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("band-qilingan") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.button, __VLS_intrinsicElements.button)({ ...{ class: ("button-container2") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.img)({ ...{ class: ("button-container-icon2") }, alt: (""), src: ("/button-container-2.svg"), });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("sotilgan") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.button, __VLS_intrinsicElements.button)({ ...{ class: ("button10") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.img)({ ...{ class: ("container-icon1") }, alt: (""), src: ("/container-1.svg"), });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("sotilmaydi") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("button11") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.img)({ ...{ class: ("container-icon2") }, alt: (""), src: ("/container-2.svg"), });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("text-input8") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("pagination") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("container1") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("slider") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("page-navigation") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("container2") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("previous-month") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("rating") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("div") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("container3") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("div1") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("container4") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("div2") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("container5") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("div3") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("container6") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("div4") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("container7") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("div5") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("container8") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("div6") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("container9") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("div7") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("calendar-container") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("paragraph-container") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("placeholder") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("podez") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("calendar row") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("col-2 yellow") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("block-text") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("col-2 yellow") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("block-text") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("col-2 yellow") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("block-text") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("col-2 yellow") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("block-text") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("col-2 red") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("block-text") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("col-2 red") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("block-text") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("col-2 red") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("block-text") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("col-2 yellow") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("block-text") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("col-2 yellow") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("block-text") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("col-2 yellow") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("block-text") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("col-2 yellow") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("block-text") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("col-2 red") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("block-text") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("col-2 empty") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("empty-text") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("col-2 yellow") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("block-text") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("col-2 yellow") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("block-text") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("col-2 yellow") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("block-text") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("col-2 red") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("block-text") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("col-2 red") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("block-text") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("col-2 empty") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("empty-text") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("col-2 empty") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("empty-text") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("col-2 empty") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("empty-text") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("col-2 empty") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("empty-text") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("col-2 empty") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("empty-text") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("col-2 empty") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("empty-text") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("col-2 empty") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("empty-text") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("col-2 empty") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("empty-text") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("col-2 empty") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("empty-text") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("col-2 empty") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("empty-text") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("col-2 empty") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("empty-text") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("col-2 empty") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("empty-text") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("col-2 empty") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("empty-text") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("col-2 empty") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("empty-text") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("col-2 empty") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("empty-text") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("container1") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("slider") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("page-navigation") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("container2") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("previous-month") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("rating") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("div") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("container3") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("div1") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("container4") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("div2") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("container5") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("div3") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("container6") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("div4") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("container7") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("div5") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("container8") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("div6") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("container9") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("div7") }, });
    __VLS_styleScopedClasses['shaxmatka'];
    __VLS_styleScopedClasses['text-input'];
    __VLS_styleScopedClasses['horizontal-container'];
    __VLS_styleScopedClasses['image-icon'];
    __VLS_styleScopedClasses['text-input-container'];
    __VLS_styleScopedClasses['hakimi-towers'];
    __VLS_styleScopedClasses['dropdown-container'];
    __VLS_styleScopedClasses['segmented-picker'];
    __VLS_styleScopedClasses['bino'];
    __VLS_styleScopedClasses['dropdown-container'];
    __VLS_styleScopedClasses['vertical-container'];
    __VLS_styleScopedClasses['vertical-container1'];
    __VLS_styleScopedClasses['close-icon'];
    __VLS_styleScopedClasses['horizontal-container1'];
    __VLS_styleScopedClasses['text-input-container1'];
    __VLS_styleScopedClasses['workspace'];
    __VLS_styleScopedClasses['text-input2'];
    __VLS_styleScopedClasses['vertical-container-icon'];
    __VLS_styleScopedClasses['qidirish'];
    __VLS_styleScopedClasses['text-input-container2'];
    __VLS_styleScopedClasses['workspace1'];
    __VLS_styleScopedClasses['text-input3'];
    __VLS_styleScopedClasses['xonalar-soni'];
    __VLS_styleScopedClasses['segmented-picker1'];
    __VLS_styleScopedClasses['button'];
    __VLS_styleScopedClasses['m2'];
    __VLS_styleScopedClasses['text-input4'];
    __VLS_styleScopedClasses['dan'];
    __VLS_styleScopedClasses['text-input5'];
    __VLS_styleScopedClasses['gacha'];
    __VLS_styleScopedClasses['segmented-picker1'];
    __VLS_styleScopedClasses['button'];
    __VLS_styleScopedClasses['m2'];
    __VLS_styleScopedClasses['text-input4'];
    __VLS_styleScopedClasses['dan'];
    __VLS_styleScopedClasses['text-input5'];
    __VLS_styleScopedClasses['gacha'];
    __VLS_styleScopedClasses['segmented-picker1'];
    __VLS_styleScopedClasses['button'];
    __VLS_styleScopedClasses['m2'];
    __VLS_styleScopedClasses['text-input4'];
    __VLS_styleScopedClasses['dan'];
    __VLS_styleScopedClasses['text-input5'];
    __VLS_styleScopedClasses['gacha'];
    __VLS_styleScopedClasses['button5'];
    __VLS_styleScopedClasses['slider-container-icon'];
    __VLS_styleScopedClasses['batafsil'];
    __VLS_styleScopedClasses['text-input-icon'];
    __VLS_styleScopedClasses['table-container'];
    __VLS_styleScopedClasses['table'];
    __VLS_styleScopedClasses['horizontal-container2'];
    __VLS_styleScopedClasses['segmented-picker3'];
    __VLS_styleScopedClasses['button6'];
    __VLS_styleScopedClasses['card-icon'];
    __VLS_styleScopedClasses['royxat'];
    __VLS_styleScopedClasses['button7'];
    __VLS_styleScopedClasses['container-icon'];
    __VLS_styleScopedClasses['shaxmatka1'];
    __VLS_styleScopedClasses['button8'];
    __VLS_styleScopedClasses['space-dashboard-icon'];
    __VLS_styleScopedClasses['shaxmatka2'];
    __VLS_styleScopedClasses['horizontal-container3'];
    __VLS_styleScopedClasses['button9'];
    __VLS_styleScopedClasses['murakkab'];
    __VLS_styleScopedClasses['vertical-container-icon1'];
    __VLS_styleScopedClasses['horizontal-container4'];
    __VLS_styleScopedClasses['xonadon'];
    __VLS_styleScopedClasses['horizontal-container5'];
    __VLS_styleScopedClasses['button-container'];
    __VLS_styleScopedClasses['button-container-icon'];
    __VLS_styleScopedClasses['bosh'];
    __VLS_styleScopedClasses['button-container1'];
    __VLS_styleScopedClasses['button-container-icon1'];
    __VLS_styleScopedClasses['band-qilingan'];
    __VLS_styleScopedClasses['button-container2'];
    __VLS_styleScopedClasses['button-container-icon2'];
    __VLS_styleScopedClasses['sotilgan'];
    __VLS_styleScopedClasses['button10'];
    __VLS_styleScopedClasses['container-icon1'];
    __VLS_styleScopedClasses['sotilmaydi'];
    __VLS_styleScopedClasses['button11'];
    __VLS_styleScopedClasses['container-icon2'];
    __VLS_styleScopedClasses['text-input8'];
    __VLS_styleScopedClasses['pagination'];
    __VLS_styleScopedClasses['container1'];
    __VLS_styleScopedClasses['slider'];
    __VLS_styleScopedClasses['page-navigation'];
    __VLS_styleScopedClasses['container2'];
    __VLS_styleScopedClasses['previous-month'];
    __VLS_styleScopedClasses['rating'];
    __VLS_styleScopedClasses['div'];
    __VLS_styleScopedClasses['container3'];
    __VLS_styleScopedClasses['div1'];
    __VLS_styleScopedClasses['container4'];
    __VLS_styleScopedClasses['div2'];
    __VLS_styleScopedClasses['container5'];
    __VLS_styleScopedClasses['div3'];
    __VLS_styleScopedClasses['container6'];
    __VLS_styleScopedClasses['div4'];
    __VLS_styleScopedClasses['container7'];
    __VLS_styleScopedClasses['div5'];
    __VLS_styleScopedClasses['container8'];
    __VLS_styleScopedClasses['div6'];
    __VLS_styleScopedClasses['container9'];
    __VLS_styleScopedClasses['div7'];
    __VLS_styleScopedClasses['calendar-container'];
    __VLS_styleScopedClasses['paragraph-container'];
    __VLS_styleScopedClasses['placeholder'];
    __VLS_styleScopedClasses['podez'];
    __VLS_styleScopedClasses['calendar'];
    __VLS_styleScopedClasses['row'];
    __VLS_styleScopedClasses['col-2'];
    __VLS_styleScopedClasses['yellow'];
    __VLS_styleScopedClasses['block-text'];
    __VLS_styleScopedClasses['col-2'];
    __VLS_styleScopedClasses['yellow'];
    __VLS_styleScopedClasses['block-text'];
    __VLS_styleScopedClasses['col-2'];
    __VLS_styleScopedClasses['yellow'];
    __VLS_styleScopedClasses['block-text'];
    __VLS_styleScopedClasses['col-2'];
    __VLS_styleScopedClasses['yellow'];
    __VLS_styleScopedClasses['block-text'];
    __VLS_styleScopedClasses['col-2'];
    __VLS_styleScopedClasses['red'];
    __VLS_styleScopedClasses['block-text'];
    __VLS_styleScopedClasses['col-2'];
    __VLS_styleScopedClasses['red'];
    __VLS_styleScopedClasses['block-text'];
    __VLS_styleScopedClasses['col-2'];
    __VLS_styleScopedClasses['red'];
    __VLS_styleScopedClasses['block-text'];
    __VLS_styleScopedClasses['col-2'];
    __VLS_styleScopedClasses['yellow'];
    __VLS_styleScopedClasses['block-text'];
    __VLS_styleScopedClasses['col-2'];
    __VLS_styleScopedClasses['yellow'];
    __VLS_styleScopedClasses['block-text'];
    __VLS_styleScopedClasses['col-2'];
    __VLS_styleScopedClasses['yellow'];
    __VLS_styleScopedClasses['block-text'];
    __VLS_styleScopedClasses['col-2'];
    __VLS_styleScopedClasses['yellow'];
    __VLS_styleScopedClasses['block-text'];
    __VLS_styleScopedClasses['col-2'];
    __VLS_styleScopedClasses['red'];
    __VLS_styleScopedClasses['block-text'];
    __VLS_styleScopedClasses['col-2'];
    __VLS_styleScopedClasses['empty'];
    __VLS_styleScopedClasses['empty-text'];
    __VLS_styleScopedClasses['col-2'];
    __VLS_styleScopedClasses['yellow'];
    __VLS_styleScopedClasses['block-text'];
    __VLS_styleScopedClasses['col-2'];
    __VLS_styleScopedClasses['yellow'];
    __VLS_styleScopedClasses['block-text'];
    __VLS_styleScopedClasses['col-2'];
    __VLS_styleScopedClasses['yellow'];
    __VLS_styleScopedClasses['block-text'];
    __VLS_styleScopedClasses['col-2'];
    __VLS_styleScopedClasses['red'];
    __VLS_styleScopedClasses['block-text'];
    __VLS_styleScopedClasses['col-2'];
    __VLS_styleScopedClasses['red'];
    __VLS_styleScopedClasses['block-text'];
    __VLS_styleScopedClasses['col-2'];
    __VLS_styleScopedClasses['empty'];
    __VLS_styleScopedClasses['empty-text'];
    __VLS_styleScopedClasses['col-2'];
    __VLS_styleScopedClasses['empty'];
    __VLS_styleScopedClasses['empty-text'];
    __VLS_styleScopedClasses['col-2'];
    __VLS_styleScopedClasses['empty'];
    __VLS_styleScopedClasses['empty-text'];
    __VLS_styleScopedClasses['col-2'];
    __VLS_styleScopedClasses['empty'];
    __VLS_styleScopedClasses['empty-text'];
    __VLS_styleScopedClasses['col-2'];
    __VLS_styleScopedClasses['empty'];
    __VLS_styleScopedClasses['empty-text'];
    __VLS_styleScopedClasses['col-2'];
    __VLS_styleScopedClasses['empty'];
    __VLS_styleScopedClasses['empty-text'];
    __VLS_styleScopedClasses['col-2'];
    __VLS_styleScopedClasses['empty'];
    __VLS_styleScopedClasses['empty-text'];
    __VLS_styleScopedClasses['col-2'];
    __VLS_styleScopedClasses['empty'];
    __VLS_styleScopedClasses['empty-text'];
    __VLS_styleScopedClasses['col-2'];
    __VLS_styleScopedClasses['empty'];
    __VLS_styleScopedClasses['empty-text'];
    __VLS_styleScopedClasses['col-2'];
    __VLS_styleScopedClasses['empty'];
    __VLS_styleScopedClasses['empty-text'];
    __VLS_styleScopedClasses['col-2'];
    __VLS_styleScopedClasses['empty'];
    __VLS_styleScopedClasses['empty-text'];
    __VLS_styleScopedClasses['col-2'];
    __VLS_styleScopedClasses['empty'];
    __VLS_styleScopedClasses['empty-text'];
    __VLS_styleScopedClasses['col-2'];
    __VLS_styleScopedClasses['empty'];
    __VLS_styleScopedClasses['empty-text'];
    __VLS_styleScopedClasses['col-2'];
    __VLS_styleScopedClasses['empty'];
    __VLS_styleScopedClasses['empty-text'];
    __VLS_styleScopedClasses['col-2'];
    __VLS_styleScopedClasses['empty'];
    __VLS_styleScopedClasses['empty-text'];
    __VLS_styleScopedClasses['container1'];
    __VLS_styleScopedClasses['slider'];
    __VLS_styleScopedClasses['page-navigation'];
    __VLS_styleScopedClasses['container2'];
    __VLS_styleScopedClasses['previous-month'];
    __VLS_styleScopedClasses['rating'];
    __VLS_styleScopedClasses['div'];
    __VLS_styleScopedClasses['container3'];
    __VLS_styleScopedClasses['div1'];
    __VLS_styleScopedClasses['container4'];
    __VLS_styleScopedClasses['div2'];
    __VLS_styleScopedClasses['container5'];
    __VLS_styleScopedClasses['div3'];
    __VLS_styleScopedClasses['container6'];
    __VLS_styleScopedClasses['div4'];
    __VLS_styleScopedClasses['container7'];
    __VLS_styleScopedClasses['div5'];
    __VLS_styleScopedClasses['container8'];
    __VLS_styleScopedClasses['div6'];
    __VLS_styleScopedClasses['container9'];
    __VLS_styleScopedClasses['div7'];
    var __VLS_slots;
    var __VLS_inheritedAttrs;
    const __VLS_refs = {};
    var $refs;
    return {
        slots: __VLS_slots,
        refs: $refs,
        attrs: {},
    };
}
;
const __VLS_self = (await import('vue')).defineComponent({
    setup() {
        return {};
    },
});
export default (await import('vue')).defineComponent({
    setup() {
        return {};
    },
});
;
//# sourceMappingURL=Shaxmatka2.vue.js.map