/// <reference types=".vue-global-types/vue_3.4_false.d.ts" />
import Header from "../components/Header.vue";
export default (await import('vue')).defineComponent({
    components: {
        Header,
    },
});
;
function __VLS_template() {
    const __VLS_ctx = {};
    const __VLS_localComponents = {
        ...{
            Header,
        },
        ...{},
        ...__VLS_ctx,
    };
    let __VLS_components;
    const __VLS_localDirectives = {
        ...{},
        ...__VLS_ctx,
    };
    let __VLS_directives;
    let __VLS_styleScopedClasses;
    // CSS variable injection 
    // CSS variable injection end 
    let __VLS_resolvedLocalAndGlobalComponents;
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("shaxmatka") }, });
    const __VLS_0 = __VLS_resolvedLocalAndGlobalComponents.Header;
    /** @type { [typeof __VLS_components.Header, ] } */
    // @ts-ignore
    const __VLS_1 = __VLS_asFunctionalComponent(__VLS_0, new __VLS_0({}));
    const __VLS_2 = __VLS_1({}, ...__VLS_functionalComponentArgsRest(__VLS_1));
    __VLS_elementAsFunction(__VLS_intrinsicElements.main, __VLS_intrinsicElements.main)({ ...{ class: ("table-container") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.section, __VLS_intrinsicElements.section)({ ...{ class: ("table") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("horizontal-container2") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("segmented-picker3") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.button, __VLS_intrinsicElements.button)({ ...{ onClick: (...[$event]) => {
                __VLS_ctx.setView('list');
            } }, ...{ class: ("button6") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.img)({ ...{ class: ("card-icon") }, alt: (""), src: ("/card.svg"), });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("royxat") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.button, __VLS_intrinsicElements.button)({ ...{ onClick: (...[$event]) => {
                __VLS_ctx.setView('grid');
            } }, ...{ class: ("button7") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.img)({ ...{ class: ("container-icon") }, alt: (""), src: ("/container.svg"), });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("shaxmatka1") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.button, __VLS_intrinsicElements.button)({ ...{ onClick: (...[$event]) => {
                __VLS_ctx.setView('gridPlus');
            } }, ...{ class: ("button8") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.img)({ ...{ class: ("space-dashboard-icon") }, alt: (""), src: ("/space-dashboard.svg"), });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("shaxmatka2") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("horizontal-container3") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("button9") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("murakkab") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.img)({ ...{ class: ("vertical-container-icon1") }, alt: (""), src: ("/vertical-container.svg"), });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("horizontal-container4") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("xonadon") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("horizontal-container5") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.button, __VLS_intrinsicElements.button)({ ...{ onClick: (...[$event]) => {
                __VLS_ctx.setStatus('bosh');
            } }, ...{ class: ("button-container") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.img)({ ...{ class: ("button-container-icon") }, alt: (""), src: ("/button-container.svg"), });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("bosh") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.button, __VLS_intrinsicElements.button)({ ...{ onClick: (...[$event]) => {
                __VLS_ctx.setStatus('band');
            } }, ...{ class: ("button-container1") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.img)({ ...{ class: ("button-container-icon1") }, alt: (""), src: ("/button-container-1.svg"), });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("band-qilingan") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.button, __VLS_intrinsicElements.button)({ ...{ onClick: (...[$event]) => {
                __VLS_ctx.setStatus('sotilgan');
            } }, ...{ class: ("button-container2") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.img)({ ...{ class: ("button-container-icon2") }, alt: (""), src: ("/button-container-2.svg"), });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("sotilgan") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.button, __VLS_intrinsicElements.button)({ ...{ onClick: (...[$event]) => {
                __VLS_ctx.setStatus('sotilmaydi');
            } }, ...{ class: ("button10") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.img)({ ...{ class: ("container-icon1") }, alt: (""), src: ("/container-1.svg"), });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("sotilmaydi") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("button11") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.img)({ ...{ class: ("container-icon2") }, alt: (""), src: ("/container-2.svg"), });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("text-input8") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("pagination") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("container1") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("slider") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("page-navigation") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("slider") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("previous-month") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("slider") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("div") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("slider") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("div1") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("slider") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("div2") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("slider") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("div3") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("slider") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("div4") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("slider") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("div5") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("slider") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("div6") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("slider") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("div7") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("calendar-container") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("paragraph-container") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("placeholder") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("podez") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("calendar row") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("col-2 yellow") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("block-text") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("col-2 yellow") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("block-text") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("col-2 yellow") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("block-text") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("col-2 yellow") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("block-text") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("col-2 red") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("block-text") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("col-2 red") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("block-text") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("col-2 red") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("block-text") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("col-2 yellow") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("block-text") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("col-2 yellow") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("block-text") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("col-2 yellow") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("block-text") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("col-2 yellow") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("block-text") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("col-2 red") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("block-text") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("col-2 empty") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("empty-text") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("col-2 yellow") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("block-text") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("col-2 yellow") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("block-text") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("col-2 yellow") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("block-text") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("col-2 red") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("block-text") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("col-2 red") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("block-text") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("col-2 empty") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("empty-text") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("col-2 empty") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("empty-text") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("col-2 empty") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("empty-text") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("col-2 empty") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("empty-text") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("col-2 empty") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("empty-text") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("col-2 empty") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("empty-text") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("col-2 empty") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("empty-text") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("col-2 empty") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("empty-text") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("col-2 empty") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("empty-text") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("col-2 empty") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("empty-text") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("col-2 empty") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("empty-text") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("col-2 empty") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("empty-text") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("col-2 empty") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("empty-text") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("col-2 empty") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("empty-text") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("col-2 empty") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("empty-text") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("container1") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("slider") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("page-navigation") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("slider") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("previous-month") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("slider") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("div") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("slider") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("div1") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("slider") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("div2") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("slider") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("div3") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("slider") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("div4") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("slider") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("div5") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("slider") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("div6") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("slider") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("div7") }, });
    __VLS_styleScopedClasses['shaxmatka'];
    __VLS_styleScopedClasses['table-container'];
    __VLS_styleScopedClasses['table'];
    __VLS_styleScopedClasses['horizontal-container2'];
    __VLS_styleScopedClasses['segmented-picker3'];
    __VLS_styleScopedClasses['button6'];
    __VLS_styleScopedClasses['card-icon'];
    __VLS_styleScopedClasses['royxat'];
    __VLS_styleScopedClasses['button7'];
    __VLS_styleScopedClasses['container-icon'];
    __VLS_styleScopedClasses['shaxmatka1'];
    __VLS_styleScopedClasses['button8'];
    __VLS_styleScopedClasses['space-dashboard-icon'];
    __VLS_styleScopedClasses['shaxmatka2'];
    __VLS_styleScopedClasses['horizontal-container3'];
    __VLS_styleScopedClasses['button9'];
    __VLS_styleScopedClasses['murakkab'];
    __VLS_styleScopedClasses['vertical-container-icon1'];
    __VLS_styleScopedClasses['horizontal-container4'];
    __VLS_styleScopedClasses['xonadon'];
    __VLS_styleScopedClasses['horizontal-container5'];
    __VLS_styleScopedClasses['button-container'];
    __VLS_styleScopedClasses['button-container-icon'];
    __VLS_styleScopedClasses['bosh'];
    __VLS_styleScopedClasses['button-container1'];
    __VLS_styleScopedClasses['button-container-icon1'];
    __VLS_styleScopedClasses['band-qilingan'];
    __VLS_styleScopedClasses['button-container2'];
    __VLS_styleScopedClasses['button-container-icon2'];
    __VLS_styleScopedClasses['sotilgan'];
    __VLS_styleScopedClasses['button10'];
    __VLS_styleScopedClasses['container-icon1'];
    __VLS_styleScopedClasses['sotilmaydi'];
    __VLS_styleScopedClasses['button11'];
    __VLS_styleScopedClasses['container-icon2'];
    __VLS_styleScopedClasses['text-input8'];
    __VLS_styleScopedClasses['pagination'];
    __VLS_styleScopedClasses['container1'];
    __VLS_styleScopedClasses['slider'];
    __VLS_styleScopedClasses['page-navigation'];
    __VLS_styleScopedClasses['slider'];
    __VLS_styleScopedClasses['previous-month'];
    __VLS_styleScopedClasses['slider'];
    __VLS_styleScopedClasses['div'];
    __VLS_styleScopedClasses['slider'];
    __VLS_styleScopedClasses['div1'];
    __VLS_styleScopedClasses['slider'];
    __VLS_styleScopedClasses['div2'];
    __VLS_styleScopedClasses['slider'];
    __VLS_styleScopedClasses['div3'];
    __VLS_styleScopedClasses['slider'];
    __VLS_styleScopedClasses['div4'];
    __VLS_styleScopedClasses['slider'];
    __VLS_styleScopedClasses['div5'];
    __VLS_styleScopedClasses['slider'];
    __VLS_styleScopedClasses['div6'];
    __VLS_styleScopedClasses['slider'];
    __VLS_styleScopedClasses['div7'];
    __VLS_styleScopedClasses['calendar-container'];
    __VLS_styleScopedClasses['paragraph-container'];
    __VLS_styleScopedClasses['placeholder'];
    __VLS_styleScopedClasses['podez'];
    __VLS_styleScopedClasses['calendar'];
    __VLS_styleScopedClasses['row'];
    __VLS_styleScopedClasses['col-2'];
    __VLS_styleScopedClasses['yellow'];
    __VLS_styleScopedClasses['block-text'];
    __VLS_styleScopedClasses['col-2'];
    __VLS_styleScopedClasses['yellow'];
    __VLS_styleScopedClasses['block-text'];
    __VLS_styleScopedClasses['col-2'];
    __VLS_styleScopedClasses['yellow'];
    __VLS_styleScopedClasses['block-text'];
    __VLS_styleScopedClasses['col-2'];
    __VLS_styleScopedClasses['yellow'];
    __VLS_styleScopedClasses['block-text'];
    __VLS_styleScopedClasses['col-2'];
    __VLS_styleScopedClasses['red'];
    __VLS_styleScopedClasses['block-text'];
    __VLS_styleScopedClasses['col-2'];
    __VLS_styleScopedClasses['red'];
    __VLS_styleScopedClasses['block-text'];
    __VLS_styleScopedClasses['col-2'];
    __VLS_styleScopedClasses['red'];
    __VLS_styleScopedClasses['block-text'];
    __VLS_styleScopedClasses['col-2'];
    __VLS_styleScopedClasses['yellow'];
    __VLS_styleScopedClasses['block-text'];
    __VLS_styleScopedClasses['col-2'];
    __VLS_styleScopedClasses['yellow'];
    __VLS_styleScopedClasses['block-text'];
    __VLS_styleScopedClasses['col-2'];
    __VLS_styleScopedClasses['yellow'];
    __VLS_styleScopedClasses['block-text'];
    __VLS_styleScopedClasses['col-2'];
    __VLS_styleScopedClasses['yellow'];
    __VLS_styleScopedClasses['block-text'];
    __VLS_styleScopedClasses['col-2'];
    __VLS_styleScopedClasses['red'];
    __VLS_styleScopedClasses['block-text'];
    __VLS_styleScopedClasses['col-2'];
    __VLS_styleScopedClasses['empty'];
    __VLS_styleScopedClasses['empty-text'];
    __VLS_styleScopedClasses['col-2'];
    __VLS_styleScopedClasses['yellow'];
    __VLS_styleScopedClasses['block-text'];
    __VLS_styleScopedClasses['col-2'];
    __VLS_styleScopedClasses['yellow'];
    __VLS_styleScopedClasses['block-text'];
    __VLS_styleScopedClasses['col-2'];
    __VLS_styleScopedClasses['yellow'];
    __VLS_styleScopedClasses['block-text'];
    __VLS_styleScopedClasses['col-2'];
    __VLS_styleScopedClasses['red'];
    __VLS_styleScopedClasses['block-text'];
    __VLS_styleScopedClasses['col-2'];
    __VLS_styleScopedClasses['red'];
    __VLS_styleScopedClasses['block-text'];
    __VLS_styleScopedClasses['col-2'];
    __VLS_styleScopedClasses['empty'];
    __VLS_styleScopedClasses['empty-text'];
    __VLS_styleScopedClasses['col-2'];
    __VLS_styleScopedClasses['empty'];
    __VLS_styleScopedClasses['empty-text'];
    __VLS_styleScopedClasses['col-2'];
    __VLS_styleScopedClasses['empty'];
    __VLS_styleScopedClasses['empty-text'];
    __VLS_styleScopedClasses['col-2'];
    __VLS_styleScopedClasses['empty'];
    __VLS_styleScopedClasses['empty-text'];
    __VLS_styleScopedClasses['col-2'];
    __VLS_styleScopedClasses['empty'];
    __VLS_styleScopedClasses['empty-text'];
    __VLS_styleScopedClasses['col-2'];
    __VLS_styleScopedClasses['empty'];
    __VLS_styleScopedClasses['empty-text'];
    __VLS_styleScopedClasses['col-2'];
    __VLS_styleScopedClasses['empty'];
    __VLS_styleScopedClasses['empty-text'];
    __VLS_styleScopedClasses['col-2'];
    __VLS_styleScopedClasses['empty'];
    __VLS_styleScopedClasses['empty-text'];
    __VLS_styleScopedClasses['col-2'];
    __VLS_styleScopedClasses['empty'];
    __VLS_styleScopedClasses['empty-text'];
    __VLS_styleScopedClasses['col-2'];
    __VLS_styleScopedClasses['empty'];
    __VLS_styleScopedClasses['empty-text'];
    __VLS_styleScopedClasses['col-2'];
    __VLS_styleScopedClasses['empty'];
    __VLS_styleScopedClasses['empty-text'];
    __VLS_styleScopedClasses['col-2'];
    __VLS_styleScopedClasses['empty'];
    __VLS_styleScopedClasses['empty-text'];
    __VLS_styleScopedClasses['col-2'];
    __VLS_styleScopedClasses['empty'];
    __VLS_styleScopedClasses['empty-text'];
    __VLS_styleScopedClasses['col-2'];
    __VLS_styleScopedClasses['empty'];
    __VLS_styleScopedClasses['empty-text'];
    __VLS_styleScopedClasses['col-2'];
    __VLS_styleScopedClasses['empty'];
    __VLS_styleScopedClasses['empty-text'];
    __VLS_styleScopedClasses['container1'];
    __VLS_styleScopedClasses['slider'];
    __VLS_styleScopedClasses['page-navigation'];
    __VLS_styleScopedClasses['slider'];
    __VLS_styleScopedClasses['previous-month'];
    __VLS_styleScopedClasses['slider'];
    __VLS_styleScopedClasses['div'];
    __VLS_styleScopedClasses['slider'];
    __VLS_styleScopedClasses['div1'];
    __VLS_styleScopedClasses['slider'];
    __VLS_styleScopedClasses['div2'];
    __VLS_styleScopedClasses['slider'];
    __VLS_styleScopedClasses['div3'];
    __VLS_styleScopedClasses['slider'];
    __VLS_styleScopedClasses['div4'];
    __VLS_styleScopedClasses['slider'];
    __VLS_styleScopedClasses['div5'];
    __VLS_styleScopedClasses['slider'];
    __VLS_styleScopedClasses['div6'];
    __VLS_styleScopedClasses['slider'];
    __VLS_styleScopedClasses['div7'];
    var __VLS_slots;
    var __VLS_inheritedAttrs;
    const __VLS_refs = {};
    var $refs;
    return {
        slots: __VLS_slots,
        refs: $refs,
        attrs: {},
    };
}
;
let __VLS_self;
//# sourceMappingURL=Shaxmatka.vue.js.map