/// <reference types=".vue-global-types/vue_3.4_false.d.ts" />
import { defineComponent } from "vue";
export default defineComponent({
    name: "FrameComponent",
});
;
function __VLS_template() {
    const __VLS_ctx = {};
    const __VLS_localComponents = {
        ...{},
        ...{},
        ...__VLS_ctx,
    };
    let __VLS_components;
    const __VLS_localDirectives = {
        ...{},
        ...__VLS_ctx,
    };
    let __VLS_directives;
    let __VLS_styleScopedClasses;
    __VLS_styleScopedClasses['b-parent6'];
    __VLS_styleScopedClasses['b-parent7'];
    __VLS_styleScopedClasses['b-parent8'];
    __VLS_styleScopedClasses['b-parent9'];
    __VLS_styleScopedClasses['b-parent10'];
    __VLS_styleScopedClasses['b-parent11'];
    __VLS_styleScopedClasses['m-parent7'];
    __VLS_styleScopedClasses['m-parent8'];
    __VLS_styleScopedClasses['m-parent9'];
    __VLS_styleScopedClasses['m-parent10'];
    __VLS_styleScopedClasses['m-parent11'];
    __VLS_styleScopedClasses['jan-parent'];
    __VLS_styleScopedClasses['chart-separators-wrapper'];
    __VLS_styleScopedClasses['line-wrapper15'];
    __VLS_styleScopedClasses['line-wrapper16'];
    __VLS_styleScopedClasses['line-wrapper17'];
    __VLS_styleScopedClasses['line-wrapper18'];
    __VLS_styleScopedClasses['line-wrapper19'];
    __VLS_styleScopedClasses['line-wrapper20'];
    __VLS_styleScopedClasses['line-wrapper21'];
    __VLS_styleScopedClasses['line-wrapper22'];
    __VLS_styleScopedClasses['line-wrapper23'];
    __VLS_styleScopedClasses['line-wrapper24'];
    __VLS_styleScopedClasses['currency-symbol'];
    __VLS_styleScopedClasses['frame-parent13'];
    __VLS_styleScopedClasses['frame-parent12'];
    __VLS_styleScopedClasses['frame-parent12'];
    // CSS variable injection 
    // CSS variable injection end 
    let __VLS_resolvedLocalAndGlobalComponents;
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("frame-parent12") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("frame-wrapper1") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("frame-parent13") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("button-wrapper1") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("button21") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.img)({ ...{ class: ("chevron-left-icon2") }, loading: ("lazy"), alt: (""), src: ("/chevron-left1.svg"), });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("button22") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.img)({ ...{ class: ("icons2") }, alt: (""), src: ("/icons.svg"), });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("currency-symbol-parent") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("currency-symbol") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("uzs57") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("button-wrapper2") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("button23") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.img)({ ...{ class: ("chevron-left-icon3") }, loading: ("lazy"), alt: (""), src: ("/chevron-left-11.svg"), });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("button24") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.img)({ ...{ class: ("icons3") }, alt: (""), src: ("/icons.svg"), });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("frame-parent14") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("frame-parent15") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("b-parent6") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("b8") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("chart-separators-wrapper") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div)({ ...{ class: ("chart-separators") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("b-parent7") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("b9") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("line-wrapper15") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div)({ ...{ class: ("frame-child54") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("b-parent8") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("b10") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("line-wrapper16") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div)({ ...{ class: ("frame-child55") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div)({ ...{ class: ("frame-child56") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("b-parent9") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("b11") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("line-wrapper17") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div)({ ...{ class: ("frame-child57") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div)({ ...{ class: ("frame-child58") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("b-parent10") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("b12") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("line-wrapper18") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div)({ ...{ class: ("frame-child59") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div)({ ...{ class: ("frame-child60") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div)({ ...{ class: ("frame-child61") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div)({ ...{ class: ("chart-title-placeholder") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("b-parent11") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("b13") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("line-wrapper19") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div)({ ...{ class: ("frame-child62") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div)({ ...{ class: ("frame-child63") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("m-parent7") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("m11") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("line-wrapper20") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div)({ ...{ class: ("frame-child64") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div)({ ...{ class: ("frame-child65") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div)({ ...{ class: ("frame-child66") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("m-parent8") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("m12") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("line-wrapper21") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div)({ ...{ class: ("frame-child67") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div)({ ...{ class: ("frame-child68") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("m-parent9") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("m13") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("line-wrapper22") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div)({ ...{ class: ("frame-child69") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div)({ ...{ class: ("frame-child70") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("m-parent10") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("m14") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("line-wrapper23") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div)({ ...{ class: ("frame-child71") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div)({ ...{ class: ("frame-child72") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("m-parent11") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("m15") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("line-wrapper24") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div)({ ...{ class: ("frame-child73") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div)({ ...{ class: ("frame-child74") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("frame-wrapper2") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("jan-parent") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("jan") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("feb") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("mar") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("apr") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("may") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("june-parent") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("june") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.input)({ ...{ class: ("selected-month-indicator") }, type: ("checkbox"), });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("contract3") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("july") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("aug10") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("sep") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("oct") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("nov") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("dec") }, });
    __VLS_styleScopedClasses['frame-parent12'];
    __VLS_styleScopedClasses['frame-wrapper1'];
    __VLS_styleScopedClasses['frame-parent13'];
    __VLS_styleScopedClasses['button-wrapper1'];
    __VLS_styleScopedClasses['button21'];
    __VLS_styleScopedClasses['chevron-left-icon2'];
    __VLS_styleScopedClasses['button22'];
    __VLS_styleScopedClasses['icons2'];
    __VLS_styleScopedClasses['currency-symbol-parent'];
    __VLS_styleScopedClasses['currency-symbol'];
    __VLS_styleScopedClasses['uzs57'];
    __VLS_styleScopedClasses['button-wrapper2'];
    __VLS_styleScopedClasses['button23'];
    __VLS_styleScopedClasses['chevron-left-icon3'];
    __VLS_styleScopedClasses['button24'];
    __VLS_styleScopedClasses['icons3'];
    __VLS_styleScopedClasses['frame-parent14'];
    __VLS_styleScopedClasses['frame-parent15'];
    __VLS_styleScopedClasses['b-parent6'];
    __VLS_styleScopedClasses['b8'];
    __VLS_styleScopedClasses['chart-separators-wrapper'];
    __VLS_styleScopedClasses['chart-separators'];
    __VLS_styleScopedClasses['b-parent7'];
    __VLS_styleScopedClasses['b9'];
    __VLS_styleScopedClasses['line-wrapper15'];
    __VLS_styleScopedClasses['frame-child54'];
    __VLS_styleScopedClasses['b-parent8'];
    __VLS_styleScopedClasses['b10'];
    __VLS_styleScopedClasses['line-wrapper16'];
    __VLS_styleScopedClasses['frame-child55'];
    __VLS_styleScopedClasses['frame-child56'];
    __VLS_styleScopedClasses['b-parent9'];
    __VLS_styleScopedClasses['b11'];
    __VLS_styleScopedClasses['line-wrapper17'];
    __VLS_styleScopedClasses['frame-child57'];
    __VLS_styleScopedClasses['frame-child58'];
    __VLS_styleScopedClasses['b-parent10'];
    __VLS_styleScopedClasses['b12'];
    __VLS_styleScopedClasses['line-wrapper18'];
    __VLS_styleScopedClasses['frame-child59'];
    __VLS_styleScopedClasses['frame-child60'];
    __VLS_styleScopedClasses['frame-child61'];
    __VLS_styleScopedClasses['chart-title-placeholder'];
    __VLS_styleScopedClasses['b-parent11'];
    __VLS_styleScopedClasses['b13'];
    __VLS_styleScopedClasses['line-wrapper19'];
    __VLS_styleScopedClasses['frame-child62'];
    __VLS_styleScopedClasses['frame-child63'];
    __VLS_styleScopedClasses['m-parent7'];
    __VLS_styleScopedClasses['m11'];
    __VLS_styleScopedClasses['line-wrapper20'];
    __VLS_styleScopedClasses['frame-child64'];
    __VLS_styleScopedClasses['frame-child65'];
    __VLS_styleScopedClasses['frame-child66'];
    __VLS_styleScopedClasses['m-parent8'];
    __VLS_styleScopedClasses['m12'];
    __VLS_styleScopedClasses['line-wrapper21'];
    __VLS_styleScopedClasses['frame-child67'];
    __VLS_styleScopedClasses['frame-child68'];
    __VLS_styleScopedClasses['m-parent9'];
    __VLS_styleScopedClasses['m13'];
    __VLS_styleScopedClasses['line-wrapper22'];
    __VLS_styleScopedClasses['frame-child69'];
    __VLS_styleScopedClasses['frame-child70'];
    __VLS_styleScopedClasses['m-parent10'];
    __VLS_styleScopedClasses['m14'];
    __VLS_styleScopedClasses['line-wrapper23'];
    __VLS_styleScopedClasses['frame-child71'];
    __VLS_styleScopedClasses['frame-child72'];
    __VLS_styleScopedClasses['m-parent11'];
    __VLS_styleScopedClasses['m15'];
    __VLS_styleScopedClasses['line-wrapper24'];
    __VLS_styleScopedClasses['frame-child73'];
    __VLS_styleScopedClasses['frame-child74'];
    __VLS_styleScopedClasses['frame-wrapper2'];
    __VLS_styleScopedClasses['jan-parent'];
    __VLS_styleScopedClasses['jan'];
    __VLS_styleScopedClasses['feb'];
    __VLS_styleScopedClasses['mar'];
    __VLS_styleScopedClasses['apr'];
    __VLS_styleScopedClasses['may'];
    __VLS_styleScopedClasses['june-parent'];
    __VLS_styleScopedClasses['june'];
    __VLS_styleScopedClasses['selected-month-indicator'];
    __VLS_styleScopedClasses['contract3'];
    __VLS_styleScopedClasses['july'];
    __VLS_styleScopedClasses['aug10'];
    __VLS_styleScopedClasses['sep'];
    __VLS_styleScopedClasses['oct'];
    __VLS_styleScopedClasses['nov'];
    __VLS_styleScopedClasses['dec'];
    var __VLS_slots;
    var __VLS_inheritedAttrs;
    const __VLS_refs = {};
    var $refs;
    return {
        slots: __VLS_slots,
        refs: $refs,
        attrs: {},
    };
}
;
let __VLS_self;
//# sourceMappingURL=FrameComponent.vue.js.map