/// <reference types=".vue-global-types/vue_3.4_false.d.ts" />
import { defineComponent } from "vue";
export default defineComponent({
    name: "Table",
    props: {
        caretDoubleLeft: { type: String },
        caretLeft: { type: String },
        caretRight: { type: String },
        caretDoubleRight: { type: String },
        caretDown: { type: String },
    },
});
;
function __VLS_template() {
    const __VLS_ctx = {};
    const __VLS_localComponents = {
        ...{},
        ...{},
        ...__VLS_ctx,
    };
    let __VLS_components;
    const __VLS_localDirectives = {
        ...{},
        ...__VLS_ctx,
    };
    let __VLS_directives;
    let __VLS_styleScopedClasses;
    __VLS_styleScopedClasses['horizontal-container4'];
    __VLS_styleScopedClasses['horizontal-container55'];
    __VLS_styleScopedClasses['text-input19'];
    __VLS_styleScopedClasses['text-input23'];
    // CSS variable injection 
    // CSS variable injection end 
    let __VLS_resolvedLocalAndGlobalComponents;
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("table") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("horizontal-container4") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.input)({ ...{ class: ("text-input19") }, placeholder: ("Date"), type: ("text"), });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("text-input20") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("cash") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("card") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("card1") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("text-input21") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("bank1") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("text-input22") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("money-transfer") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.input)({ ...{ class: ("text-input23") }, placeholder: ("Boshqa"), type: ("text"), });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("horizontal-container5") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("text-input24") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("aug") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("rating-container") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("rating") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("uzs7") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("horizontal-container6") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("horizontal-container7") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("uzs8") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("container10") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("uzs9") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("horizontal-container8") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("uzs10") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("horizontal-container9") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("uzs11") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("horizontal-container10") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("text-input25") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("aug1") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("rating-container1") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("rating1") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("uzs12") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("horizontal-container11") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("horizontal-container12") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("uzs13") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("container11") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("uzs14") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("horizontal-container13") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("uzs15") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("horizontal-container14") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("uzs16") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("horizontal-container15") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("text-input26") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("aug2") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("rating-container2") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("rating2") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("uzs17") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("horizontal-container16") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("horizontal-container17") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("uzs18") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("container12") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("uzs19") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("horizontal-container18") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("uzs20") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("horizontal-container19") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("uzs21") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("horizontal-container20") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("text-input27") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("aug3") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("rating-container3") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("rating3") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("uzs22") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("horizontal-container21") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("horizontal-container22") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("uzs23") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("container13") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("uzs24") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("horizontal-container23") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("uzs25") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("horizontal-container24") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("uzs26") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("horizontal-container25") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("text-input28") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("aug4") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("rating-container4") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("rating4") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("uzs27") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("horizontal-container26") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("horizontal-container27") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("uzs28") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("container14") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("uzs29") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("horizontal-container28") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("uzs30") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("horizontal-container29") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("uzs31") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("horizontal-container30") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("text-input29") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("aug5") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("rating-container5") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("rating5") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("uzs32") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("horizontal-container31") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("horizontal-container32") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("uzs33") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("container15") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("uzs34") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("horizontal-container33") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("uzs35") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("horizontal-container34") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("uzs36") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("horizontal-container35") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("text-input30") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("aug6") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("rating-container6") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("rating6") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("uzs37") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("horizontal-container36") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("horizontal-container37") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("uzs38") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("container16") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("uzs39") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("horizontal-container38") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("uzs40") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("horizontal-container39") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("uzs41") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("horizontal-container40") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("text-input31") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("aug7") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("rating-container7") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("rating7") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("uzs42") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("horizontal-container41") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("horizontal-container42") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("uzs43") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("container17") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("uzs44") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("horizontal-container43") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("uzs45") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("horizontal-container44") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("uzs46") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("horizontal-container45") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("text-input32") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("aug8") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("rating-container8") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("rating8") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("uzs47") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("horizontal-container46") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("horizontal-container47") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("uzs48") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("container18") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("uzs49") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("horizontal-container48") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("uzs50") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("horizontal-container49") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("uzs51") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("horizontal-container50") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("text-input33") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("aug9") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("rating-container9") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("rating9") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("uzs52") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("horizontal-container51") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("horizontal-container52") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("uzs53") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("container19") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("uzs54") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("horizontal-container53") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("uzs55") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("horizontal-container54") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("uzs56") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("horizontal-container55") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("page-1-of") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("segmented-picker-container") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("container20") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.img)({ ...{ class: ("caretdoubleleft-icon") }, loading: ("lazy"), alt: (""), src: ((__VLS_ctx.caretDoubleLeft)), });
    __VLS_elementAsFunction(__VLS_intrinsicElements.img)({ ...{ class: ("caretleft-icon") }, loading: ("lazy"), alt: (""), src: ((__VLS_ctx.caretLeft)), });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("segmented-picker4") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("pagination-base") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("page-number") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("pagination-base1") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("div28") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("pagination-base2") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("div29") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("container21") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.img)({ ...{ class: ("caretright-icon") }, loading: ("lazy"), alt: (""), src: ((__VLS_ctx.caretRight)), });
    __VLS_elementAsFunction(__VLS_intrinsicElements.img)({ ...{ class: ("caretdoubleright-icon") }, loading: ("lazy"), alt: (""), src: ((__VLS_ctx.caretDoubleRight)), });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("button-container1") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("show") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("button20") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("dropdown-label") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.img)({ ...{ class: ("caretdown-icon") }, alt: (""), src: ((__VLS_ctx.caretDown)), });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("page") }, });
    __VLS_styleScopedClasses['table'];
    __VLS_styleScopedClasses['horizontal-container4'];
    __VLS_styleScopedClasses['text-input19'];
    __VLS_styleScopedClasses['text-input20'];
    __VLS_styleScopedClasses['cash'];
    __VLS_styleScopedClasses['card'];
    __VLS_styleScopedClasses['card1'];
    __VLS_styleScopedClasses['text-input21'];
    __VLS_styleScopedClasses['bank1'];
    __VLS_styleScopedClasses['text-input22'];
    __VLS_styleScopedClasses['money-transfer'];
    __VLS_styleScopedClasses['text-input23'];
    __VLS_styleScopedClasses['horizontal-container5'];
    __VLS_styleScopedClasses['text-input24'];
    __VLS_styleScopedClasses['aug'];
    __VLS_styleScopedClasses['rating-container'];
    __VLS_styleScopedClasses['rating'];
    __VLS_styleScopedClasses['uzs7'];
    __VLS_styleScopedClasses['horizontal-container6'];
    __VLS_styleScopedClasses['horizontal-container7'];
    __VLS_styleScopedClasses['uzs8'];
    __VLS_styleScopedClasses['container10'];
    __VLS_styleScopedClasses['uzs9'];
    __VLS_styleScopedClasses['horizontal-container8'];
    __VLS_styleScopedClasses['uzs10'];
    __VLS_styleScopedClasses['horizontal-container9'];
    __VLS_styleScopedClasses['uzs11'];
    __VLS_styleScopedClasses['horizontal-container10'];
    __VLS_styleScopedClasses['text-input25'];
    __VLS_styleScopedClasses['aug1'];
    __VLS_styleScopedClasses['rating-container1'];
    __VLS_styleScopedClasses['rating1'];
    __VLS_styleScopedClasses['uzs12'];
    __VLS_styleScopedClasses['horizontal-container11'];
    __VLS_styleScopedClasses['horizontal-container12'];
    __VLS_styleScopedClasses['uzs13'];
    __VLS_styleScopedClasses['container11'];
    __VLS_styleScopedClasses['uzs14'];
    __VLS_styleScopedClasses['horizontal-container13'];
    __VLS_styleScopedClasses['uzs15'];
    __VLS_styleScopedClasses['horizontal-container14'];
    __VLS_styleScopedClasses['uzs16'];
    __VLS_styleScopedClasses['horizontal-container15'];
    __VLS_styleScopedClasses['text-input26'];
    __VLS_styleScopedClasses['aug2'];
    __VLS_styleScopedClasses['rating-container2'];
    __VLS_styleScopedClasses['rating2'];
    __VLS_styleScopedClasses['uzs17'];
    __VLS_styleScopedClasses['horizontal-container16'];
    __VLS_styleScopedClasses['horizontal-container17'];
    __VLS_styleScopedClasses['uzs18'];
    __VLS_styleScopedClasses['container12'];
    __VLS_styleScopedClasses['uzs19'];
    __VLS_styleScopedClasses['horizontal-container18'];
    __VLS_styleScopedClasses['uzs20'];
    __VLS_styleScopedClasses['horizontal-container19'];
    __VLS_styleScopedClasses['uzs21'];
    __VLS_styleScopedClasses['horizontal-container20'];
    __VLS_styleScopedClasses['text-input27'];
    __VLS_styleScopedClasses['aug3'];
    __VLS_styleScopedClasses['rating-container3'];
    __VLS_styleScopedClasses['rating3'];
    __VLS_styleScopedClasses['uzs22'];
    __VLS_styleScopedClasses['horizontal-container21'];
    __VLS_styleScopedClasses['horizontal-container22'];
    __VLS_styleScopedClasses['uzs23'];
    __VLS_styleScopedClasses['container13'];
    __VLS_styleScopedClasses['uzs24'];
    __VLS_styleScopedClasses['horizontal-container23'];
    __VLS_styleScopedClasses['uzs25'];
    __VLS_styleScopedClasses['horizontal-container24'];
    __VLS_styleScopedClasses['uzs26'];
    __VLS_styleScopedClasses['horizontal-container25'];
    __VLS_styleScopedClasses['text-input28'];
    __VLS_styleScopedClasses['aug4'];
    __VLS_styleScopedClasses['rating-container4'];
    __VLS_styleScopedClasses['rating4'];
    __VLS_styleScopedClasses['uzs27'];
    __VLS_styleScopedClasses['horizontal-container26'];
    __VLS_styleScopedClasses['horizontal-container27'];
    __VLS_styleScopedClasses['uzs28'];
    __VLS_styleScopedClasses['container14'];
    __VLS_styleScopedClasses['uzs29'];
    __VLS_styleScopedClasses['horizontal-container28'];
    __VLS_styleScopedClasses['uzs30'];
    __VLS_styleScopedClasses['horizontal-container29'];
    __VLS_styleScopedClasses['uzs31'];
    __VLS_styleScopedClasses['horizontal-container30'];
    __VLS_styleScopedClasses['text-input29'];
    __VLS_styleScopedClasses['aug5'];
    __VLS_styleScopedClasses['rating-container5'];
    __VLS_styleScopedClasses['rating5'];
    __VLS_styleScopedClasses['uzs32'];
    __VLS_styleScopedClasses['horizontal-container31'];
    __VLS_styleScopedClasses['horizontal-container32'];
    __VLS_styleScopedClasses['uzs33'];
    __VLS_styleScopedClasses['container15'];
    __VLS_styleScopedClasses['uzs34'];
    __VLS_styleScopedClasses['horizontal-container33'];
    __VLS_styleScopedClasses['uzs35'];
    __VLS_styleScopedClasses['horizontal-container34'];
    __VLS_styleScopedClasses['uzs36'];
    __VLS_styleScopedClasses['horizontal-container35'];
    __VLS_styleScopedClasses['text-input30'];
    __VLS_styleScopedClasses['aug6'];
    __VLS_styleScopedClasses['rating-container6'];
    __VLS_styleScopedClasses['rating6'];
    __VLS_styleScopedClasses['uzs37'];
    __VLS_styleScopedClasses['horizontal-container36'];
    __VLS_styleScopedClasses['horizontal-container37'];
    __VLS_styleScopedClasses['uzs38'];
    __VLS_styleScopedClasses['container16'];
    __VLS_styleScopedClasses['uzs39'];
    __VLS_styleScopedClasses['horizontal-container38'];
    __VLS_styleScopedClasses['uzs40'];
    __VLS_styleScopedClasses['horizontal-container39'];
    __VLS_styleScopedClasses['uzs41'];
    __VLS_styleScopedClasses['horizontal-container40'];
    __VLS_styleScopedClasses['text-input31'];
    __VLS_styleScopedClasses['aug7'];
    __VLS_styleScopedClasses['rating-container7'];
    __VLS_styleScopedClasses['rating7'];
    __VLS_styleScopedClasses['uzs42'];
    __VLS_styleScopedClasses['horizontal-container41'];
    __VLS_styleScopedClasses['horizontal-container42'];
    __VLS_styleScopedClasses['uzs43'];
    __VLS_styleScopedClasses['container17'];
    __VLS_styleScopedClasses['uzs44'];
    __VLS_styleScopedClasses['horizontal-container43'];
    __VLS_styleScopedClasses['uzs45'];
    __VLS_styleScopedClasses['horizontal-container44'];
    __VLS_styleScopedClasses['uzs46'];
    __VLS_styleScopedClasses['horizontal-container45'];
    __VLS_styleScopedClasses['text-input32'];
    __VLS_styleScopedClasses['aug8'];
    __VLS_styleScopedClasses['rating-container8'];
    __VLS_styleScopedClasses['rating8'];
    __VLS_styleScopedClasses['uzs47'];
    __VLS_styleScopedClasses['horizontal-container46'];
    __VLS_styleScopedClasses['horizontal-container47'];
    __VLS_styleScopedClasses['uzs48'];
    __VLS_styleScopedClasses['container18'];
    __VLS_styleScopedClasses['uzs49'];
    __VLS_styleScopedClasses['horizontal-container48'];
    __VLS_styleScopedClasses['uzs50'];
    __VLS_styleScopedClasses['horizontal-container49'];
    __VLS_styleScopedClasses['uzs51'];
    __VLS_styleScopedClasses['horizontal-container50'];
    __VLS_styleScopedClasses['text-input33'];
    __VLS_styleScopedClasses['aug9'];
    __VLS_styleScopedClasses['rating-container9'];
    __VLS_styleScopedClasses['rating9'];
    __VLS_styleScopedClasses['uzs52'];
    __VLS_styleScopedClasses['horizontal-container51'];
    __VLS_styleScopedClasses['horizontal-container52'];
    __VLS_styleScopedClasses['uzs53'];
    __VLS_styleScopedClasses['container19'];
    __VLS_styleScopedClasses['uzs54'];
    __VLS_styleScopedClasses['horizontal-container53'];
    __VLS_styleScopedClasses['uzs55'];
    __VLS_styleScopedClasses['horizontal-container54'];
    __VLS_styleScopedClasses['uzs56'];
    __VLS_styleScopedClasses['horizontal-container55'];
    __VLS_styleScopedClasses['page-1-of'];
    __VLS_styleScopedClasses['segmented-picker-container'];
    __VLS_styleScopedClasses['container20'];
    __VLS_styleScopedClasses['caretdoubleleft-icon'];
    __VLS_styleScopedClasses['caretleft-icon'];
    __VLS_styleScopedClasses['segmented-picker4'];
    __VLS_styleScopedClasses['pagination-base'];
    __VLS_styleScopedClasses['page-number'];
    __VLS_styleScopedClasses['pagination-base1'];
    __VLS_styleScopedClasses['div28'];
    __VLS_styleScopedClasses['pagination-base2'];
    __VLS_styleScopedClasses['div29'];
    __VLS_styleScopedClasses['container21'];
    __VLS_styleScopedClasses['caretright-icon'];
    __VLS_styleScopedClasses['caretdoubleright-icon'];
    __VLS_styleScopedClasses['button-container1'];
    __VLS_styleScopedClasses['show'];
    __VLS_styleScopedClasses['button20'];
    __VLS_styleScopedClasses['dropdown-label'];
    __VLS_styleScopedClasses['caretdown-icon'];
    __VLS_styleScopedClasses['page'];
    var __VLS_slots;
    var __VLS_inheritedAttrs;
    const __VLS_refs = {};
    var $refs;
    return {
        slots: __VLS_slots,
        refs: $refs,
        attrs: {},
    };
}
;
let __VLS_self;
//# sourceMappingURL=Table.vue.js.map