/// <reference types=".vue-global-types/vue_3.4_false.d.ts" />
import { defineComponent } from "vue";
export default defineComponent({
    name: "TableNavigation",
});
;
function __VLS_template() {
    const __VLS_ctx = {};
    const __VLS_localComponents = {
        ...{},
        ...{},
        ...__VLS_ctx,
    };
    let __VLS_components;
    const __VLS_localDirectives = {
        ...{},
        ...__VLS_ctx,
    };
    let __VLS_directives;
    let __VLS_styleScopedClasses;
    __VLS_styleScopedClasses['chart-label'];
    __VLS_styleScopedClasses['column-data'];
    __VLS_styleScopedClasses['m-group'];
    __VLS_styleScopedClasses['m-container'];
    __VLS_styleScopedClasses['m-parent1'];
    __VLS_styleScopedClasses['m-parent2'];
    __VLS_styleScopedClasses['m-parent3'];
    __VLS_styleScopedClasses['m-parent4'];
    __VLS_styleScopedClasses['m-parent5'];
    __VLS_styleScopedClasses['m-parent6'];
    __VLS_styleScopedClasses['parent'];
    __VLS_styleScopedClasses['legend-item-details'];
    __VLS_styleScopedClasses['legend-item-content-parent'];
    __VLS_styleScopedClasses['chart-legend'];
    __VLS_styleScopedClasses['table-navigation'];
    __VLS_styleScopedClasses['august-2024'];
    __VLS_styleScopedClasses['navigation-buttons'];
    __VLS_styleScopedClasses['table-navigation'];
    __VLS_styleScopedClasses['label-divider'];
    __VLS_styleScopedClasses['column-data-inner'];
    __VLS_styleScopedClasses['line-wrapper7'];
    __VLS_styleScopedClasses['line-wrapper8'];
    __VLS_styleScopedClasses['line-wrapper9'];
    __VLS_styleScopedClasses['line-wrapper10'];
    __VLS_styleScopedClasses['line-wrapper11'];
    __VLS_styleScopedClasses['line-wrapper12'];
    __VLS_styleScopedClasses['line-wrapper13'];
    __VLS_styleScopedClasses['line-wrapper14'];
    __VLS_styleScopedClasses['chart-legend'];
    // CSS variable injection 
    // CSS variable injection end 
    let __VLS_resolvedLocalAndGlobalComponents;
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("table-navigation") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("previous-navigation") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("navigation-buttons") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("button-wrapper") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("button16") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.img)({ ...{ class: ("chevron-left-icon") }, loading: ("lazy"), alt: (""), src: ("/chevron-left.svg"), });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("button17") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.img)({ ...{ class: ("icons") }, alt: (""), src: ("/icons.svg"), });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("date-container") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("august-2024") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("uzs6") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("button-frame") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("button18") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.img)({ ...{ class: ("chevron-left-icon1") }, loading: ("lazy"), alt: (""), src: ("/chevron-left-1.svg"), });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("button19") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.img)({ ...{ class: ("icons1") }, alt: (""), src: ("/icons.svg"), });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("data-visualization") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("chart") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("chart-label") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("m1") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("label-divider") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div)({ ...{ class: ("label-divider-child") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("chart-columns") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("column-data") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("m2") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("column-data-inner") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div)({ ...{ class: ("frame-child16") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div)({ ...{ class: ("column-data-child") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div)({ ...{ class: ("column-data-item") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("chart-columns1") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("m-group") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("m3") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("line-wrapper7") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div)({ ...{ class: ("frame-child17") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div)({ ...{ class: ("frame-child18") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div)({ ...{ class: ("frame-child19") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div)({ ...{ class: ("frame-child20") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("chart-inner") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("m-container") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("m4") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("line-wrapper8") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div)({ ...{ class: ("frame-child21") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div)({ ...{ class: ("frame-child22") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div)({ ...{ class: ("frame-child23") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div)({ ...{ class: ("frame-child24") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div)({ ...{ class: ("frame-child25") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div)({ ...{ class: ("frame-child26") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div)({ ...{ class: ("frame-child27") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div)({ ...{ class: ("frame-child28") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div)({ ...{ class: ("frame-child29") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div)({ ...{ class: ("frame-child30") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div)({ ...{ class: ("frame-child31") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("chart-columns2") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("m-parent1") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("m5") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("line-wrapper9") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div)({ ...{ class: ("frame-child32") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div)({ ...{ class: ("frame-child33") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div)({ ...{ class: ("frame-child34") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div)({ ...{ class: ("frame-child35") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("chart-child") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("m-parent2") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("m6") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("line-wrapper10") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div)({ ...{ class: ("frame-child36") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div)({ ...{ class: ("frame-child37") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div)({ ...{ class: ("frame-child38") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div)({ ...{ class: ("frame-child39") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div)({ ...{ class: ("frame-child40") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div)({ ...{ class: ("frame-child41") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("chart-columns3") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("m-parent3") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("m7") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("line-wrapper11") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div)({ ...{ class: ("frame-child42") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div)({ ...{ class: ("frame-child43") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div)({ ...{ class: ("frame-child44") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div)({ ...{ class: ("frame-child45") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("chart-columns4") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("m-parent4") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("m8") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("line-wrapper12") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div)({ ...{ class: ("frame-child46") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div)({ ...{ class: ("frame-child47") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div)({ ...{ class: ("frame-child48") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("chart-columns5") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("m-parent5") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("m9") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("line-wrapper13") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div)({ ...{ class: ("frame-child49") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div)({ ...{ class: ("frame-child50") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div)({ ...{ class: ("frame-child51") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("chart-inner1") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("m-parent6") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("m10") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("line-wrapper14") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div)({ ...{ class: ("frame-child52") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div)({ ...{ class: ("frame-child53") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("data-visualization-inner") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("parent") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("div14") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("div15") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("div16") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("div17") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("div18") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("div19") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("div20") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("div21") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("div22") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("div23") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("div24") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("div25") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("div26") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("div27") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("chart-legend") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("legend-label-parent") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("legend-label") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.input)({ ...{ class: ("legend-color") }, type: ("checkbox"), });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("legend-item-content-parent") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("legend-item-content") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("legend-item-details") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("legend-item-values") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("legend-item-values1") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("legend-item-values2") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("legend-item-values3") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("legend-item-values4") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("legend-item-values5") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("legend-item-values6") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("legend-item-values7") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("legend-item-values8") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("legend-item-values9") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("legend-item-values10") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("legend-item-values11") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("legend-item-values12") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("legend-item-values13") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("legend-item-values14") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("legend-item-values15") }, });
    __VLS_elementAsFunction(__VLS_intrinsicElements.div, __VLS_intrinsicElements.div)({ ...{ class: ("contract2") }, });
    __VLS_styleScopedClasses['table-navigation'];
    __VLS_styleScopedClasses['previous-navigation'];
    __VLS_styleScopedClasses['navigation-buttons'];
    __VLS_styleScopedClasses['button-wrapper'];
    __VLS_styleScopedClasses['button16'];
    __VLS_styleScopedClasses['chevron-left-icon'];
    __VLS_styleScopedClasses['button17'];
    __VLS_styleScopedClasses['icons'];
    __VLS_styleScopedClasses['date-container'];
    __VLS_styleScopedClasses['august-2024'];
    __VLS_styleScopedClasses['uzs6'];
    __VLS_styleScopedClasses['button-frame'];
    __VLS_styleScopedClasses['button18'];
    __VLS_styleScopedClasses['chevron-left-icon1'];
    __VLS_styleScopedClasses['button19'];
    __VLS_styleScopedClasses['icons1'];
    __VLS_styleScopedClasses['data-visualization'];
    __VLS_styleScopedClasses['chart'];
    __VLS_styleScopedClasses['chart-label'];
    __VLS_styleScopedClasses['m1'];
    __VLS_styleScopedClasses['label-divider'];
    __VLS_styleScopedClasses['label-divider-child'];
    __VLS_styleScopedClasses['chart-columns'];
    __VLS_styleScopedClasses['column-data'];
    __VLS_styleScopedClasses['m2'];
    __VLS_styleScopedClasses['column-data-inner'];
    __VLS_styleScopedClasses['frame-child16'];
    __VLS_styleScopedClasses['column-data-child'];
    __VLS_styleScopedClasses['column-data-item'];
    __VLS_styleScopedClasses['chart-columns1'];
    __VLS_styleScopedClasses['m-group'];
    __VLS_styleScopedClasses['m3'];
    __VLS_styleScopedClasses['line-wrapper7'];
    __VLS_styleScopedClasses['frame-child17'];
    __VLS_styleScopedClasses['frame-child18'];
    __VLS_styleScopedClasses['frame-child19'];
    __VLS_styleScopedClasses['frame-child20'];
    __VLS_styleScopedClasses['chart-inner'];
    __VLS_styleScopedClasses['m-container'];
    __VLS_styleScopedClasses['m4'];
    __VLS_styleScopedClasses['line-wrapper8'];
    __VLS_styleScopedClasses['frame-child21'];
    __VLS_styleScopedClasses['frame-child22'];
    __VLS_styleScopedClasses['frame-child23'];
    __VLS_styleScopedClasses['frame-child24'];
    __VLS_styleScopedClasses['frame-child25'];
    __VLS_styleScopedClasses['frame-child26'];
    __VLS_styleScopedClasses['frame-child27'];
    __VLS_styleScopedClasses['frame-child28'];
    __VLS_styleScopedClasses['frame-child29'];
    __VLS_styleScopedClasses['frame-child30'];
    __VLS_styleScopedClasses['frame-child31'];
    __VLS_styleScopedClasses['chart-columns2'];
    __VLS_styleScopedClasses['m-parent1'];
    __VLS_styleScopedClasses['m5'];
    __VLS_styleScopedClasses['line-wrapper9'];
    __VLS_styleScopedClasses['frame-child32'];
    __VLS_styleScopedClasses['frame-child33'];
    __VLS_styleScopedClasses['frame-child34'];
    __VLS_styleScopedClasses['frame-child35'];
    __VLS_styleScopedClasses['chart-child'];
    __VLS_styleScopedClasses['m-parent2'];
    __VLS_styleScopedClasses['m6'];
    __VLS_styleScopedClasses['line-wrapper10'];
    __VLS_styleScopedClasses['frame-child36'];
    __VLS_styleScopedClasses['frame-child37'];
    __VLS_styleScopedClasses['frame-child38'];
    __VLS_styleScopedClasses['frame-child39'];
    __VLS_styleScopedClasses['frame-child40'];
    __VLS_styleScopedClasses['frame-child41'];
    __VLS_styleScopedClasses['chart-columns3'];
    __VLS_styleScopedClasses['m-parent3'];
    __VLS_styleScopedClasses['m7'];
    __VLS_styleScopedClasses['line-wrapper11'];
    __VLS_styleScopedClasses['frame-child42'];
    __VLS_styleScopedClasses['frame-child43'];
    __VLS_styleScopedClasses['frame-child44'];
    __VLS_styleScopedClasses['frame-child45'];
    __VLS_styleScopedClasses['chart-columns4'];
    __VLS_styleScopedClasses['m-parent4'];
    __VLS_styleScopedClasses['m8'];
    __VLS_styleScopedClasses['line-wrapper12'];
    __VLS_styleScopedClasses['frame-child46'];
    __VLS_styleScopedClasses['frame-child47'];
    __VLS_styleScopedClasses['frame-child48'];
    __VLS_styleScopedClasses['chart-columns5'];
    __VLS_styleScopedClasses['m-parent5'];
    __VLS_styleScopedClasses['m9'];
    __VLS_styleScopedClasses['line-wrapper13'];
    __VLS_styleScopedClasses['frame-child49'];
    __VLS_styleScopedClasses['frame-child50'];
    __VLS_styleScopedClasses['frame-child51'];
    __VLS_styleScopedClasses['chart-inner1'];
    __VLS_styleScopedClasses['m-parent6'];
    __VLS_styleScopedClasses['m10'];
    __VLS_styleScopedClasses['line-wrapper14'];
    __VLS_styleScopedClasses['frame-child52'];
    __VLS_styleScopedClasses['frame-child53'];
    __VLS_styleScopedClasses['data-visualization-inner'];
    __VLS_styleScopedClasses['parent'];
    __VLS_styleScopedClasses['div14'];
    __VLS_styleScopedClasses['div15'];
    __VLS_styleScopedClasses['div16'];
    __VLS_styleScopedClasses['div17'];
    __VLS_styleScopedClasses['div18'];
    __VLS_styleScopedClasses['div19'];
    __VLS_styleScopedClasses['div20'];
    __VLS_styleScopedClasses['div21'];
    __VLS_styleScopedClasses['div22'];
    __VLS_styleScopedClasses['div23'];
    __VLS_styleScopedClasses['div24'];
    __VLS_styleScopedClasses['div25'];
    __VLS_styleScopedClasses['div26'];
    __VLS_styleScopedClasses['div27'];
    __VLS_styleScopedClasses['chart-legend'];
    __VLS_styleScopedClasses['legend-label-parent'];
    __VLS_styleScopedClasses['legend-label'];
    __VLS_styleScopedClasses['legend-color'];
    __VLS_styleScopedClasses['legend-item-content-parent'];
    __VLS_styleScopedClasses['legend-item-content'];
    __VLS_styleScopedClasses['legend-item-details'];
    __VLS_styleScopedClasses['legend-item-values'];
    __VLS_styleScopedClasses['legend-item-values1'];
    __VLS_styleScopedClasses['legend-item-values2'];
    __VLS_styleScopedClasses['legend-item-values3'];
    __VLS_styleScopedClasses['legend-item-values4'];
    __VLS_styleScopedClasses['legend-item-values5'];
    __VLS_styleScopedClasses['legend-item-values6'];
    __VLS_styleScopedClasses['legend-item-values7'];
    __VLS_styleScopedClasses['legend-item-values8'];
    __VLS_styleScopedClasses['legend-item-values9'];
    __VLS_styleScopedClasses['legend-item-values10'];
    __VLS_styleScopedClasses['legend-item-values11'];
    __VLS_styleScopedClasses['legend-item-values12'];
    __VLS_styleScopedClasses['legend-item-values13'];
    __VLS_styleScopedClasses['legend-item-values14'];
    __VLS_styleScopedClasses['legend-item-values15'];
    __VLS_styleScopedClasses['contract2'];
    var __VLS_slots;
    var __VLS_inheritedAttrs;
    const __VLS_refs = {};
    var $refs;
    return {
        slots: __VLS_slots,
        refs: $refs,
        attrs: {},
    };
}
;
let __VLS_self;
//# sourceMappingURL=TableNavigation.vue.js.map